### ISSUE TITLE
LOGO-Net Dataset

### ISSUE THREAD

**Issue by alantaitz** [Heldenkombinat/Logodetect#34]
Hi thanks for such an impressive model! 
I am interested on running the provided notebooks. It looks like the LOGO-Net dataset is not publicly available. Is there a sample of this dataset I could use to run these notebooks? Or an explanation of how this datasets is structured so I can make a similar small dataset and run the notebooks on it.
Thanks!

**Comment by maxpumperla** [comment]
@jorgedch anything we can do about this?

**Comment by jorgedch** [comment]
Hi @alantaitz! Unfortunately the dataset is not publicly available, so we had to contact directly the authors to ask them for access. We are not allowed to share it, but you could reach them out as well. Their contacts are in the website http://www.mysmu.edu.sg/faculty/chhoi/logonet/

Otherwise, you can test the notebooks with a dataset that you make or to adapt the annotations format of a publicly available one. The conventions are:
- The image file and the annotations file have the same name
- Images have the extension `.jpg` and annotations the extension `.txt`
- Annotation files have the coordinates of a rectangle around a logo and the brand name in every row as follows:
    - `top_left_x_coord top_left_y_coord bottom_right_x_coord bottom_right_y_coord brand_name`
    - E.g. `5 5 150 150 Red_Bull_with-text` or `50 5 100 100 Red_Bull_without-text`
    - You can have sub-classes for each brand name, as sometimes the same brand have variations of a logo, but the notebooks will parse them as separate brands
- The values in each row are separated by spaces, so if a brand name has more than one word it has to be separated with an underscore or so

Cheers!

**Comment by alantaitz** [comment]
This is super useful! thanks a lot for the answer.
